// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pcbuilder.Api.Data;

#nullable disable

namespace Pcbuilder.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pcbuilder.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("EstPowerW")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PerfScore")
                        .HasColumnType("numeric");

                    b.Property<bool>("PowerSafe")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UpgradabilityScore")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("builds", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<short?>("UseCaseId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MarketId");

                    b.HasIndex("UseCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("build_activity", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildPart", b =>
                {
                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("BuildId", "PartId");

                    b.HasIndex("PartId");

                    b.ToTable("build_parts", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("PerformanceScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PowerSafetyScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceEfficiency")
                        .HasColumnType("numeric");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Upgradability")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("RequestId", "Rank")
                        .IsUnique();

                    b.ToTable("build_recommendations", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BudgetMin")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<short>("UseCaseId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("UseCaseId");

                    b.HasIndex("UserId");

                    b.ToTable("build_requests", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildWarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("build_warnings", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.CaseSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("FormFactorSupport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxCoolerHeightMm")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxGpuLengthMm")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("case_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.CoolerSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int?>("HeightMm")
                        .HasColumnType("integer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MaxTdpWatts")
                        .HasColumnType("integer");

                    b.Property<string>("SocketSupport")
                        .HasColumnType("text");

                    b.HasKey("PartId");

                    b.ToTable("cooler_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.CpuSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BaseGhz")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BoostGhz")
                        .HasColumnType("numeric");

                    b.Property<int>("Cores")
                        .HasColumnType("integer");

                    b.Property<bool>("Igpu")
                        .HasColumnType("boolean");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Threads")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("cpu_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.GpuSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LengthMm")
                        .HasColumnType("integer");

                    b.Property<int?>("PcieGen")
                        .HasColumnType("integer");

                    b.Property<int?>("RecommendedPsuWatts")
                        .HasColumnType("integer");

                    b.Property<int>("VramGb")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("gpu_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.MotherboardSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chipset")
                        .HasColumnType("text");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("M2Slots")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxMemoryGb")
                        .HasColumnType("integer");

                    b.Property<int>("MemorySlots")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SataPorts")
                        .HasColumnType("integer");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PartId");

                    b.ToTable("motherboard_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Msrp")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PerfScore")
                        .HasColumnType("numeric");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<int?>("TdpWatts")
                        .HasColumnType("integer");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("TypeId", "Brand", "Model");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.PartOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("InStock")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.HasIndex("MarketId", "InStock");

                    b.HasIndex("PartId", "MarketId");

                    b.ToTable("part_offers", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.PartType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("part_types", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.PsuSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("Efficiency")
                        .HasColumnType("text");

                    b.Property<bool?>("Modular")
                        .HasColumnType("boolean");

                    b.Property<int>("Wattage")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("psu_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.RamSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer");

                    b.Property<string>("MemoryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SpeedMhz")
                        .HasColumnType("integer");

                    b.Property<int>("Sticks")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("ram_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.StorageSpec", b =>
                {
                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityGb")
                        .HasColumnType("integer");

                    b.Property<string>("Interface")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SeqReadMbS")
                        .HasColumnType("integer");

                    b.HasKey("PartId");

                    b.ToTable("storage_specs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("FpsGain")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FpsGainPerCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FromBuildId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PowerSafetyScore")
                        .HasColumnType("numeric");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ResaleValueEst")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ToBuildId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromBuildId");

                    b.HasIndex("ToBuildId");

                    b.HasIndex("RequestId", "Rank")
                        .IsUnique();

                    b.ToTable("upgrade_plans", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradePlanChange", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeType")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("PlanId", "PartId", "ChangeType");

                    b.HasIndex("PartId");

                    b.ToTable("upgrade_plan_changes", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BudgetMax")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserPcId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("UserPcId");

                    b.ToTable("upgrade_requests", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UseCase", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("use_cases", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UserPc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.HasIndex("UserId");

                    b.ToTable("user_pcs", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Build", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildActivity", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pcbuilder.Api.Models.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pcbuilder.Api.Models.UseCase", "UseCase")
                        .WithMany()
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pcbuilder.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Build");

                    b.Navigation("Market");

                    b.Navigation("UseCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildPart", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Build", "Build")
                        .WithMany("BuildParts")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildRecommendation", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.BuildRequest", "Request")
                        .WithMany("Recommendations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildRequest", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.UseCase", "UseCase")
                        .WithMany()
                        .HasForeignKey("UseCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Market");

                    b.Navigation("UseCase");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildWarning", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Build", "Build")
                        .WithMany("Warnings")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.CaseSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("CaseSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.CaseSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.CoolerSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("CoolerSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.CoolerSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.CpuSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("CpuSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.CpuSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.GpuSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("GpuSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.GpuSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.MotherboardSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("MotherboardSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.MotherboardSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Part", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.PartType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.PartOffer", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("Part");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.PsuSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("PsuSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.PsuSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.RamSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("RamSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.RamSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.StorageSpec", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithOne("StorageSpec")
                        .HasForeignKey("Pcbuilder.Api.Models.StorageSpec", "PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradePlan", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Build", "FromBuild")
                        .WithMany()
                        .HasForeignKey("FromBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.UpgradeRequest", "Request")
                        .WithMany("Plans")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.Build", "ToBuild")
                        .WithMany()
                        .HasForeignKey("ToBuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBuild");

                    b.Navigation("Request");

                    b.Navigation("ToBuild");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradePlanChange", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Part", "Part")
                        .WithMany()
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.UpgradePlan", "Plan")
                        .WithMany("Changes")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradeRequest", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Market", "Market")
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.UserPc", "UserPc")
                        .WithMany("UpgradeRequests")
                        .HasForeignKey("UserPcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("UserPc");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UserPc", b =>
                {
                    b.HasOne("Pcbuilder.Api.Models.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pcbuilder.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Build", b =>
                {
                    b.Navigation("BuildParts");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.BuildRequest", b =>
                {
                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.Part", b =>
                {
                    b.Navigation("CaseSpec");

                    b.Navigation("CoolerSpec");

                    b.Navigation("CpuSpec");

                    b.Navigation("GpuSpec");

                    b.Navigation("MotherboardSpec");

                    b.Navigation("PsuSpec");

                    b.Navigation("RamSpec");

                    b.Navigation("StorageSpec");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradePlan", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UpgradeRequest", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("Pcbuilder.Api.Models.UserPc", b =>
                {
                    b.Navigation("UpgradeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
